//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaterial
    {
        public int IdOrMat { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Order Order { get; set; }
    }
}
